//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtalonFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manag()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int m_ID { get; set; }
        public string m_surname { get; set; }
        public string m_name { get; set; }
        public string m_patronymic { get; set; }
        public string m_fullname
        {
            get => $"{ m_surname} { m_name} { m_patronymic}";
        }
        public string m_phone { get; set; }
        public string m_email { get; set; }
        public int m_userID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
