//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtalonFM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int o_ID { get; set; }
        public int o_managerID { get; set; }
        public int o_clientID { get; set; }
        public int o_typeID { get; set; }
        public int o_locationID { get; set; }
        public int o_duration { get; set; }
        public decimal o_cost { get; set; }
        public System.DateTime o_dateStart { get; set; }
        public System.DateTime o_dateEnd { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual Client Client { get; set; }
        public virtual Location Location { get; set; }
        public virtual Manag Manag { get; set; }
    }
}
